<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="run on firefox"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="20.439">
  <properties />
            <testcase name="TC_01_Register" time="8.940" classname="takeScreenshot.Level_16_Register_Login_Screenshot_ExtentReportV2">
                <failure type="java.lang.AssertionError"
                  message="expected [Your registration completed.] but found [Your registration completed]"
              >
<![CDATA[java.lang.AssertionError: expected [Your registration completed.] but found [Your registration completed]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertEqualsImpl(Assert.java:137)
  org.testng.Assert.assertEquals(Assert.java:118)
  org.testng.Assert.assertEquals(Assert.java:453)
  org.testng.Assert.assertEquals(Assert.java:463)
  takeScreenshot.Level_16_Register_Login_Screenshot_ExtentReportV2.TC_01_Register(Level_16_Register_Login_Screenshot_ExtentReportV2.java:82)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  java.base/java.lang.Thread.run(Thread.java:832)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_02_Login" time="9.974" classname="takeScreenshot.Level_16_Register_Login_Screenshot_ExtentReportV2" />
                <testcase name="TC_03_MyAccount" time="1.525" classname="takeScreenshot.Level_16_Register_Login_Screenshot_ExtentReportV2" />
      
</testsuite>
